// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// findUnmodCoverageCpp
List findUnmodCoverageCpp(List cov_reads, List cov_strands, List mod_reads, CharacterVector ref_strands);
RcppExport SEXP _DMRcaller_findUnmodCoverageCpp(SEXP cov_readsSEXP, SEXP cov_strandsSEXP, SEXP mod_readsSEXP, SEXP ref_strandsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cov_reads(cov_readsSEXP);
    Rcpp::traits::input_parameter< List >::type cov_strands(cov_strandsSEXP);
    Rcpp::traits::input_parameter< List >::type mod_reads(mod_readsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ref_strands(ref_strandsSEXP);
    rcpp_result_gen = Rcpp::wrap(findUnmodCoverageCpp(cov_reads, cov_strands, mod_reads, ref_strands));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DMRcaller_findUnmodCoverageCpp", (DL_FUNC) &_DMRcaller_findUnmodCoverageCpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DMRcaller(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
